### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by alexanderadam** [markusdd/ilo-utils#1]
Hi Markus,

I guess it would nice to have a solution that works within a Docker container. Maybe one of [the existing FireFox Dockerfiles](https://github.com/search?q=firefox+java+language%3ADockerfile&type=repositories&l=Dockerfile) could be used as a base.
This way people wouldn't have to bother with local Java installations and the existing shell scripts could still be used.

Thank you so much for these scripts :open_hands:

**Comment by markusdd** [comment]
doing this within docker is not straightforward because of the way I have to get the java install going. it is dodgy as it is.

Also, I have personally no longer access to ilo3/4 machines for testing, so if there is any interest in this one would need to provide a PR.

Personally, I do not see a large issue as the java install goes into a isolated subdir and does not pollute the system path, but if anyone wants to go through the trouble of writing and testing a Dockerfile I am more than happy to accept a pull request.

**Comment by alexanderadam** [comment]
You're right. I'm gonna close this.
