### ISSUE TITLE
curl: (35) error:0A0C0103:SSL routines::internal error Failed to retrieve key. Wrong password or banned?

### ISSUE THREAD

**Issue by 9r00t-z** [markusdd/ilo-utils#3]
Hello, VERY COOL piece of software, makes my life so much easier !!!

Although, I'm not sure what I'm doing wrong with the console proxy.  I read through a fair number of times and re-setup everything from scratch.  I can access the web UI problem (which is awesome by the way).  But, I can't seem to get console to work.  I know it's "functional" cuz I have an iPhone app that allows console access, but for some reason I can't get the proxy to work.  I get the following error running it on Ubuntu 22.04

curl: (35) error:0A0C0103:SSL routines::internal error
Failed to retrieve key. Wrong password or banned?

Any tips for me ?

TIA

**Comment by markusdd** [comment]
Glad it is useful!

On newer distributions this is almost always a problem with disabled/missing etc SSL ciphers.

This whole setup is very flaky because these iLo interfaces use crypto that is considered largely outdated.

My recommendation for debugging: maybe try spinning up a VM with a 2018 LTS Ubuntu or a centOS 7 and then see if it works there with the way you are doing it. If yes, then you know you probably need some magic SSL cipher options to make it work on Ubuntu 22.
